services:
  - type: web
    name: carpark-finder-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GOV_API_KEY
        sync: false
      - key: DATA_GOV_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: PORT
        value: 10000
      - key: DEBUG
        value: False
      - key: HOST
        value: 0.0.0.0
    plan: starter
    region: singapore
    autoDeploy: true
